# Generated by Django 4.1.1 on 2022-09-15 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('rolPerfil', models.CharField(max_length=35, verbose_name='RolPerfil')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=35, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=35, verbose_name='Telefono')),
                ('genero', models.CharField(max_length=35, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=35, verbose_name='ciudad')),
                ('fecha_Nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=35, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_signos')),
                ('oximetria', models.CharField(max_length=50, verbose_name='oximetria')),
                ('frecuencia_respiratoria', models.CharField(max_length=50, verbose_name='frecuencia_respiratoria')),
                ('frecuencia_cardiaca', models.CharField(max_length=50, verbose_name='frecuencia_cardiaca')),
                ('temperatura', models.CharField(max_length=50, verbose_name='temperatura')),
                ('glicemias', models.CharField(max_length=50, verbose_name='glicemia')),
                ('presion_arterial', models.CharField(max_length=50, verbose_name='presion')),
                ('fecha_hora', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id_personalSalud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=35, verbose_name='rol')),
                ('especialidad', models.CharField(max_length=35, verbose_name='especialidad')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perSalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_personalSalud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.personalsalud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia_clinica', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_HistoriaClinica')),
                ('sugerencias_cuidado', models.TextField()),
                ('diagnostico', models.TextField()),
                ('entorno', models.TextField()),
                ('fecha_de_sugerencia', models.DateField()),
                ('descripcion', models.TextField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_Familiar')),
                ('parentesco', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('correo', models.EmailField(max_length=100, verbose_name='Email')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.paciente')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
