# Generated by Django 4.1.1 on 2022-09-12 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('rolPerfil', models.CharField(max_length=35, verbose_name='rolPerfil')),
                ('nombre', models.CharField(max_length=35, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=35, verbose_name='apellidos')),
                ('telefono', models.CharField(max_length=35, verbose_name='telefono')),
                ('genero', models.CharField(max_length=35, verbose_name='genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id_personalSalud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=35, verbose_name='rol')),
                ('especialidad', models.CharField(max_length=35, verbose_name='especialidad')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perSalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=35, verbose_name='ciudad')),
                ('fecha_Nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=35, verbose_name='direccion')),
                ('id_personalSalud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.personalsalud')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
